name: build

on:
  push:
    branches:
      - master
      - main

jobs:
  build-linux:
    container: "python:3.9"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install pyoxidizer==0.18.0

          pyoxidizer build

          cp -r build/x86_64-unknown-linux-gnu/debug/install "build/vantage-3.4.1-linux"
          chmod +x "build/vantage-3.4.1-linux/vantage"
          cp install.sh README.md LICENSE "build/vantage-3.4.1-linux/"

          cd build
          tar -cvzf "vantage-3.4.1-linux.tar.gz" "vantage-3.4.1-linux"
      
      - uses: actions/upload-artifact@v3
        with:
          name: vantage-3.4.1-linux.tar.gz
          path: build/vantage-3.4.1-linux.tar.gz
  
  # build-mac-intel:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Install vantage
  #       run: |
  #         wget https://github.com/vantage-org/vantage/releases/download/v3.3.0/vantage-3.3.0-macos.tar.gz
  #         tar xzf vantage-3.3.0-macos.tar.gz
  #         cd vantage-3.3.0-macos
  #         sudo ./install.sh
      
  #     - name: Build
  #       run: vg -v VERSION=3.4.0 build macos_x86
      
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: vantage-3.4.0-macos.tar.gz
  #         path: build/vantage-3.4.0-macos.tar.gz